/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:28edb89a-d138-4c30-bdc2-07e2bac45f42",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_X5a1MJ5AL",
    "aws_user_pools_web_client_id": "3pciqotli0dpej9mo2rh9ebuip",
    "oauth": {}
};


export default awsmobile;
